### ISSUE TITLE
Cursor breaks in Atom 1.1.0

### ISSUE THREAD

**Issue by MethodGrab** [squizlabs/atom-innerspace#4]
atom-innerspace: 0.1.5

After updating to Atom 1.1.0, the cursor doesn't work correctly. It's often not visible or cannot be positioned with the mouse. Disabling atom-innerspace fixes the issue.

**Comment by danny-peters** [comment]
I have noticed this same problem lately. But I don't have inner space installed. Often switching tabs alone will fix it. Sometimes the app needs to be restarted. I think it's a core atom bug.

**Comment by MethodGrab** [comment]
I tried closing projects/tabs/windows/restarting several times and the only way to fix it was to disable atom-innerspace. It looks like someone else also has this problem:

> Had a problem with cursor position too, since 1.1.
> Found that https://atom.io/packages/atom-innerspace was the cause, uninstalled it, problem solved. — @jeekajoo [https://github.com/atom/atom/issues/9343#issuecomment-152485919]

**Comment by alexbet** [comment]
I have the same issue after installing Atom 1.1.0. I isolated the issue to the atom-innerspace plugin. When I disable the plugin, the cursor works fine.

**Comment by sertand** [comment]
I can confirm that cursor is not working properly after installing Atom 1.1.0..

**Comment by ebramanti** [comment]
Thanks @MethodGrab for logging this. I've been struggling to use my editor and was unable to determine for a bit which package was causing the problem.

**Comment by Yoshi325** [comment]
Gotta pile on this bandwagon. I am also experiencing this issue. Frustratingly there was no error message indicating the problem, so finding this issue was quite a trek.

**Comment by sertand** [comment]
I had a look at this and it seems like Atom is calculating the position of the cursor incorrectly.. It positions the cursor off screen when Innerspace inserts the whitespace characters in between words. At this point I don't think there is anything I can do but I will try contacting one of the Atom developers to see if anything can be done.

Sorry for the inconvenience everyone :(

**Comment by ebramanti** [comment]
@sertand It's OK, just glad I was able to figure out this issue.

**Comment by zmts** [comment]
After update to Atom v1.2 
This bug Repeats

**Comment by alexbet** [comment]
+1 after Atom 1.2

**Comment by jagalbraith** [comment]
I am jumping in here. I use Atom on both Windows and Mac side by side and I experienced this problem on both.

**Comment by ebramanti** [comment]
If this is still broken, we might want to put a note in the README.

**Comment by sertand** [comment]
I had to unpublish this plugin as there is no way to fix the issue due to the changes that have been made in Atom v1.1.0. It is good that Atom has this feature built in now.

**Comment by MethodGrab** [comment]
Where is the built-in option?

**Comment by ebramanti** [comment]
+1 to @MethodGrab's question

**Comment by jagalbraith** [comment]
The built in option is called show invisibles. You may have to upgrade your Atom version to get this if you are running an old build. The only problem is the functionality is not all there that innerspace did have. What I am talking about is the dot between all the elements showing spaces. This is very helpful in Bash scripting when you are dealing with $1 $2 $3 and so on. To view this {WINDOWS} Go in to settings and scroll down to show invisibles. {MAC/LINUX} Go in to preferences and scroll down to show invisibles.

**Comment by ebramanti** [comment]
@MethodGrab @jagalbraith Correct, looks like this still is not solved https://github.com/atom/atom/issues/2572

**Comment by jagalbraith** [comment]
@jadengore Great correlation on this issue. Yes, this doesn't seem to be solved at all. Although, It is functioning as designed so it really shouldn't be considered a bug, rather, a feature request.

**Comment by MethodGrab** [comment]
@jadengore thanks for the link!
