### ISSUE TITLE
Not present on atom.io, is this working?

### ISSUE THREAD

**Issue by fractalf** [squizlabs/atom-innerspace#6]
Is there something wrong with this package since it is not listed here:

https://atom.io/packages/search?utf8=%E2%9C%93&q=atom-innerspace

**Comment by gsherwood** [comment]
It used to be listed, but the plugin stopped working a while ago thanks to an Atom upgrade. We contacted the Atom dev team and they said they wouldn't be making any changes to make this plugin possible again, so it has been abandoned.

**Comment by fractalf** [comment]
Ok, thanks. I also found an issue over at https://github.com/atom/atom/issues/12157 which deals with my problem of weird invisible characters.
